name: Basic CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify files
        run: echo "Project files checked successfully"

      - name: List files
        run: ls -la
